_target_: real_robot_env.robot.hardware_depthai.DepthAI
device_id: "1844301051D9B50F00"
name: "centric_cam"
height: 512
width: 512
log_interval: 60
publish_topic: "/centric_cam"
camera_type: 
  _target_: real_robot_env.robot.hardware_depthai.DAICameraType.__getitem__
  name: OAK_D_LITE